= Description of the Chosen System

Put sussinctly, the C3 System is a communication system backed by a network of heliocentric satellites connected with optical laser links that will provide interplanetary communication, computer network infrastructure for the Mars colony, and real time communication for astronauts on the surface of Mars.

There are 3 main use cases the system is designed to support:
+ High throughput message delivery for transferring large amounts of data between the colony and Earth.
+ Data streaming for probes at potentially extra-solar distances.
+ Real time short range communication for interpersonal communication on the colony.

These use cases have different requirements and constraints. To meet all of them, the system is comprised of different communication methods designed to integrate with each other.
+ *High Throughput Message Queue (HTMQ)*: This protocol is designed to transfer large amounts of data between the colony and Earth. It is designed to be reliable and to have a high throughput. All messages that enter the queue are guaranteed to be delivered to the recipient. It is not designed to be low latency, but it will adequately handle the high latency of the Earth-Mars communication link. It is designed to be used for transferring large amounts of data, such as scientific data, large files, and other data that is not time sensitive. All HTMQ traffic is to be encrypted by default.
+ *Data Streaming Protocol (DSP)*: This protocol is designed to stream metric data from probes, and issue commands to probes. It is designed to easy for a link to be established to minimize time wasted on establishing a connection (no handshaking). Because of the low transmission power of probes, it is designed to be robust to packet loss and signal degradation, which will result in a lower throughput.
+ *IP Network*: This is a commercial computer network designed to be used for real time and asynchronous communication between people on the colony. It is designed to be low latency and high throughput. It is designed to be reliable, and fast. It is not designed to be encrypted by default, but it can be encrypted if desired. This will allow for compatibility with existing internet protocols and software.
+ *Short Range Radio (SRR)*: This protocol is designed to be used for real time audio/video communication between the colony and astronauts on the surface of Mars. It is designed to be low latency and simple to implement (no handshaking). This is to work similar to a walkie-talkie, where the user can simply press a button to start transmitting, or have continuous 2 way communication. It is not necessarily designed to be reliable, as in it won't guarantee transmission delivery, but it is designed to be fast. It is not designed to be encrypted by default, but it can be encrypted if desired. This will allow for compatibility with existing radio protocols and software.
