name: Build

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: yusancky/setup-typst@v2
        id: setup-typst
        with:
          version: "v0.11.0"
      - run: sudo apt-get install -y make
      - run: typst compile main.typ
      - uses: actions/upload-artifact@v2
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        with:
          name: main.pdf
          path: main.pdf

  lint-capnp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get install -y capnproto
      - run: find . -name "*.capnp" -exec capnp compile -ocapnp {} \;

  typos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: typos-action
        uses: crate-ci/typos@v1.19.0
