name: Lint

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm install -g @mermaid-js/mermaid-cli@10.6.1
      - run: sudo apt-get install -y graphviz
      - name: Ensure generated files are up to date
        run: ./scripts/ensure-generated.sh
